use radiust_core::config::CoreConfig;
use radiust_core::engine::{Engine, EngineError};
use radiust_core::errors::CoreError;
use radiust_core::identity::{logical_id, safe_ref};
use radiust_core::model::FrameRef;
use radiust_core::source::SourceRegistry;
use serde_json::json;
use sha2::{Digest, Sha256};
use std::fs;
use std::path::{Path, PathBuf};

const TW_GRID_BYTES: &[u8] =
    include_bytes!("../../../tests/fixtures/sources/tw/raw/O-A0059-001.json");

fn tw_grid_ref() -> FrameRef {
    let revision = "O-A0059-001-1789878600";
    let mut frame = FrameRef {
        source: "tw".into(),
        product: "grid".into(),
        station: Some("CV1_3600".into()),
        valid_time: "2026-09-20T04:30:00.000000Z".into(),
        base_time: None,
        logical_id: String::new(),
        revision: Some(revision.into()),
        locator_version: "tw-legacy-v1".into(),
        locator: json!({
            "url": "https://cwaopendata.s3.ap-northeast-1.amazonaws.com/Observation/O-A0059-001.json",
            "artifacts": [],
            "station": "CV1_3600",
            "revision": revision,
        }),
    };
    frame.logical_id = logical_id(&frame).expect("retained TW fixture identity");
    frame
}

fn write_python_compatible_manifest(root: &Path, corrupt: bool) -> PathBuf {
    let raw_root = root.join("raw");
    fs::create_dir_all(&raw_root).expect("create raw fixture root");
    let payload_path = raw_root.join("O-A0059-001.json");
    let mut payload = TW_GRID_BYTES.to_vec();
    if corrupt {
        payload[0] ^= 1;
    }
    fs::write(&payload_path, payload).expect("write retained TW fixture bytes");

    let frame = tw_grid_ref();
    let document = json!({
        "schema_version": 1,
        "ref": safe_ref(&frame).expect("serialize Python-compatible safe ref"),
        "artifacts": [{
            "name": "O-A0059-001.json",
            "role": "data",
            "media_type": "application/json",
            "size_bytes": TW_GRID_BYTES.len(),
            "sha256": hex::encode(Sha256::digest(TW_GRID_BYTES)),
            "source_revision": null,
        }],
        "metadata": {},
        "raw_complete": true,
    });
    let path = root.join("raw-manifest.json");
    fs::write(&path, serde_json::to_vec_pretty(&document).unwrap())
        .expect("write v1 raw manifest generated by the Python schema");
    path
}

fn read_manifest(path: &Path) -> serde_json::Value {
    serde_json::from_slice(&fs::read(path).expect("read raw manifest")).expect("parse raw manifest")
}

fn write_manifest(path: &Path, document: &serde_json::Value) {
    fs::write(path, serde_json::to_vec_pretty(document).expect("serialize raw manifest"))
        .expect("write raw manifest");
}

fn offline_engine(root: &Path) -> Engine {
    let mut config = CoreConfig::default();
    config.runtime.allow_network = false;
    config.runtime.temp_root = Some(root.join("rust-staging"));
    config.cache.enabled = false;
    Engine::new(config, SourceRegistry::default()).expect("construct offline Rust Engine")
}

fn assert_staging_empty(root: &Path) {
    let staging = root.join("rust-staging");
    if staging.exists() {
        assert!(staging.is_dir());
        assert_eq!(fs::read_dir(staging).unwrap().count(), 0);
    }
}

async fn assert_manifest_rejected(engine: &Engine, manifest: PathBuf) {
    let error = engine.replay_raw_manifest(manifest).await.unwrap_err();
    assert!(matches!(error, EngineError::Core(CoreError::Storage(_))));
}

#[tokio::test]
async fn rust_replays_the_same_retained_python_tw_raw_fixture_offline() {
    let root = tempfile::tempdir().unwrap();
    let manifest = write_python_compatible_manifest(root.path(), false);
    let engine = offline_engine(root.path());

    let field = engine.replay_raw_manifest(manifest).await.expect("decode retained offline raw");
    assert_eq!(field.name, "reflectivity");
    assert_eq!(field.shape, [881, 921]);
    assert_eq!(field.units.as_deref(), Some("dBZ"));
    assert_eq!(field.grid.crs.as_deref(), Some("EPSG:3821"));
    assert_staging_empty(root.path());
}

#[tokio::test]
async fn corrupt_python_compatible_fixture_is_rejected_and_staging_is_removed() {
    let root = tempfile::tempdir().unwrap();
    let manifest = write_python_compatible_manifest(root.path(), true);
    let engine = offline_engine(root.path());

    let error = engine.replay_raw_manifest(manifest).await.unwrap_err();
    assert!(matches!(error, EngineError::Core(CoreError::Storage(_))));
    assert_staging_empty(root.path());
}

#[tokio::test]
async fn replay_rejects_hash_and_size_receipt_mismatches() {
    let root = tempfile::tempdir().unwrap();
    let engine = offline_engine(root.path());

    let hash_root = root.path().join("bad-hash");
    fs::create_dir_all(&hash_root).unwrap();
    let hash_manifest = write_python_compatible_manifest(&hash_root, false);
    let mut document = read_manifest(&hash_manifest);
    document["artifacts"][0]["sha256"] = json!("0".repeat(64));
    write_manifest(&hash_manifest, &document);
    assert_manifest_rejected(&engine, hash_manifest).await;

    let size_root = root.path().join("bad-size");
    fs::create_dir_all(&size_root).unwrap();
    let size_manifest = write_python_compatible_manifest(&size_root, false);
    let mut document = read_manifest(&size_manifest);
    document["artifacts"][0]["size_bytes"] = json!(TW_GRID_BYTES.len() + 1);
    write_manifest(&size_manifest, &document);
    assert_manifest_rejected(&engine, size_manifest).await;

    assert_staging_empty(root.path());
}

#[tokio::test]
async fn replay_rejects_incomplete_and_empty_manifests() {
    let root = tempfile::tempdir().unwrap();
    let engine = offline_engine(root.path());

    let incomplete_root = root.path().join("incomplete");
    fs::create_dir_all(&incomplete_root).unwrap();
    let incomplete_manifest = write_python_compatible_manifest(&incomplete_root, false);
    let mut document = read_manifest(&incomplete_manifest);
    document["raw_complete"] = json!(false);
    write_manifest(&incomplete_manifest, &document);
    assert_manifest_rejected(&engine, incomplete_manifest).await;

    let empty_root = root.path().join("empty");
    fs::create_dir_all(&empty_root).unwrap();
    let empty_manifest = write_python_compatible_manifest(&empty_root, false);
    let mut document = read_manifest(&empty_manifest);
    document["artifacts"] = json!([]);
    write_manifest(&empty_manifest, &document);
    assert_manifest_rejected(&engine, empty_manifest).await;

    assert_staging_empty(root.path());
}

#[tokio::test]
async fn replay_rejects_path_traversal_and_symlink_escape() {
    let root = tempfile::tempdir().unwrap();
    let engine = offline_engine(root.path());

    let traversal_root = root.path().join("traversal");
    fs::create_dir_all(&traversal_root).unwrap();
    let traversal_manifest = write_python_compatible_manifest(&traversal_root, false);
    let mut document = read_manifest(&traversal_manifest);
    document["artifacts"][0]["name"] = json!("../outside.json");
    write_manifest(&traversal_manifest, &document);
    assert_manifest_rejected(&engine, traversal_manifest).await;

    #[cfg(unix)]
    {
        let symlink_root = root.path().join("symlink");
        fs::create_dir_all(&symlink_root).unwrap();
        let symlink_manifest = write_python_compatible_manifest(&symlink_root, false);
        let artifact = symlink_root.join("raw/O-A0059-001.json");
        let outside = root.path().join("outside.json");
        fs::write(&outside, TW_GRID_BYTES).unwrap();
        fs::remove_file(&artifact).unwrap();
        std::os::unix::fs::symlink(&outside, &artifact).unwrap();
        assert_manifest_rejected(&engine, symlink_manifest).await;
    }

    assert_staging_empty(root.path());
}

#[tokio::test]
async fn replay_requires_the_manifest_filename_and_valid_json() {
    let root = tempfile::tempdir().unwrap();
    let engine = offline_engine(root.path());
    let manifest = write_python_compatible_manifest(root.path(), false);

    let wrong_name = root.path().join("manifest.json");
    fs::copy(&manifest, &wrong_name).unwrap();
    assert_manifest_rejected(&engine, wrong_name).await;

    fs::write(&manifest, b"{").unwrap();
    assert_manifest_rejected(&engine, manifest).await;

    assert_staging_empty(root.path());
}

#[tokio::test]
async fn cancellation_after_replay_staging_drops_the_verified_raw_artifact() {
    let root = tempfile::tempdir().unwrap();
    let manifest = write_python_compatible_manifest(root.path(), false);
    let engine = offline_engine(root.path());
    engine.cancel();

    let error = engine.replay_raw_manifest(manifest).await.unwrap_err();
    assert!(matches!(error, EngineError::Core(CoreError::Cancelled)));
    assert_staging_empty(root.path());
}
