"""Independent radar data acquisition and processing toolkit."""

from .api import (
    adownload,
    afetch,
    afetch_many,
    aiter_fetch,
    download,
    fetch,
    fetch_many,
    iter_fetch,
    render_field,
    show,
)
from .client import AsyncClient, Client
from .errors import (
    AmbiguousFrameError,
    AsyncContextError,
    AuthenticationError,
    BatchError,
    ConfigError,
    DecodeError,
    DuplicateSourceError,
    GeoreferencingError,
    GridError,
    IntegrityError,
    MissingDependencyError,
    NoDataError,
    OutputConflict,
    OutputLockedError,
    RadiustError,
    ResourceLimitError,
    StaleFrameError,
    StorageError,
    TransportError,
    UnknownColorError,
    UnsupportedQueryError,
)
from .field import RadarDataset, RadarField
from .grids import CartesianGrid, CurvilinearGrid, GeographicGrid, Grid, PolarGrid
from .models import (
    Artifact,
    BatchResult,
    DownloadReport,
    FrameRef,
    FrameResult,
    OutputRequest,
    ProcessingSpec,
    ProductInfo,
    Query,
    SourceInfo,
    StationInfo,
)
from .registry import get_source, sources

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "Client",
    "AsyncClient",
    "Query",
    "FrameRef",
    "SourceInfo",
    "ProductInfo",
    "StationInfo",
    "Artifact",
    "ProcessingSpec",
    "OutputRequest",
    "FrameResult",
    "BatchResult",
    "DownloadReport",
    "RadarField",
    "RadarDataset",
    "Grid",
    "GeographicGrid",
    "CartesianGrid",
    "PolarGrid",
    "CurvilinearGrid",
    "sources",
    "get_source",
    "fetch",
    "afetch",
    "fetch_many",
    "afetch_many",
    "iter_fetch",
    "aiter_fetch",
    "download",
    "adownload",
    "render_field",
    "show",
    "RadiustError",
    "ConfigError",
    "MissingDependencyError",
    "UnsupportedQueryError",
    "AsyncContextError",
    "NoDataError",
    "StaleFrameError",
    "AmbiguousFrameError",
    "AuthenticationError",
    "TransportError",
    "IntegrityError",
    "ResourceLimitError",
    "UnknownColorError",
    "DecodeError",
    "GridError",
    "GeoreferencingError",
    "OutputConflict",
    "OutputLockedError",
    "StorageError",
    "DuplicateSourceError",
    "BatchError",
]
